import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
    {
        ignores: [
            'dist', // autogenerated by Nuxt
            '.output', // autogenerated by Nuxt
            '.nuxt', // autogenerated by Nuxt
            'node_modules',
        ],
    },
).append({
    files: ['**/*.stories.vue'],
    rules: {
        'vue/multi-word-component-names': 'off',
    },
}).override('nuxt/stylistic', {
    rules: {
        '@stylistic/function-paren-newline': ['error', 'consistent'],
        '@stylistic/indent': ['error', 4],
        '@stylistic/quotes': ['error', 'single'],
        '@stylistic/semi': ['error', 'never'],
        '@stylistic/comma-dangle': ['error', 'always-multiline'],
        '@stylistic/brace-style': ['error', '1tbs'],
        '@stylistic/object-curly-spacing': ['error', 'always'],
        '@stylistic/array-bracket-spacing': ['error', 'never'],
    },
}).override('nuxt/vue/rules', {
    rules: {
        'vue/max-len': ['warn', {
            code: 120,
            ignoreUrls: true,
            ignoreStrings: true,
            ignoreTemplateLiterals: true,
            ignoreTrailingComments: true,
            ignoreHTMLAttributeValues: true,
        }],
    },
}).append({
    files: ['**/*.ts', '**/*.js', '**/*.mjs', '**/*.jsx', '**/*.tsx'],
    rules: {
        '@stylistic/max-len': ['warn', {
            code: 120,
            ignoreUrls: true,
            ignoreStrings: true,
            ignoreTemplateLiterals: true,
            ignoreTrailingComments: true,
        }],
    },
})
