import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
    {
        ignores: [
            'dist', // autogenerated by Nuxt
            '.output', // autogenerated by Nuxt
            '.nuxt', // autogenerated by Nuxt
            'node_modules',
        ],
    },
).append({
    files: ['./app/**/*.stories.vue'],
    rules: {
        'vue/multi-word-component-names': 'off',
    },
}).override('nuxt/stylistic', {
    rules: {
        '@stylistic/function-paren-newline': ['error', 'consistent'],
    },
}).override('nuxt/vue/rules', {
    rules: {
        'vue/max-len': ['warn', {
            code: 120,
            ignoreUrls: true,
            ignoreStrings: true,
            ignoreTemplateLiterals: true,
            ignoreTrailingComments: true,
            ignoreHTMLAttributeValues: true,
        }],
    },
}).append({
    files: ['**/*.ts', '**/*.js', '**/*.mjs', '**/*.jsx', '**/*.tsx'],
    rules: {
        '@stylistic/max-len': ['warn', {
            code: 120,
            ignoreUrls: true,
            ignoreStrings: true,
            ignoreTemplateLiterals: true,
            ignoreTrailingComments: true,
        }],
    },
})
// .override('nuxt/typescript/rules', {
//     rules: {
//         '@typescript-eslint/no-empty-object-type': ['error', {
//             allowInterfaces: 'with-single-extends',
//         }],
//     },
// })
